FROM openfaas/of-watchdog:0.7.2 as watchdog

FROM okteto/golang:1

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

RUN addgroup --gid 12000 app && \
    adduser --home /home/app --uid 12000 --gid 12000 app

USER app
RUN mkdir -p /home/app/handler/function
COPY build/hello/main.go /home/app/handler
COPY build/hello/go.mod  /home/app/handler

ENV fprocess="./handler"
ENV mode="http"
ENV upstream_url="http://127.0.0.1:8082"

WORKDIR /home/app/handler/function
CMD ["./fwatchdog"]